extends: default

rules:
  line-length:
    max: 120
  document-start: disable
  document-end: disable
  truthy:
    allowed-values: [true, false]
    check-keys: false
  comments:
    min-spaces-from-content: 1
  indentation:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: false